- name: Install Kafka parcel
  hosts: localhost
  gather_facts: False
  tags:
    - install_kafka
  roles:
    - cdh_install_parcels:
        cm_host: 172.18.50.214
        cm_user: admin
        cm_pass: admin
        api_version: 10
        repositories:
          - http://archive.cloudera.com/kafka/parcels/1.4.0/
        parcels:
          KAFKA: 0.8.2.0-1.kafka1.4.0.p0.56
      register: results
    - debug: var=results
