- name: Add Kafka repo
  hosts: localhost
  gather_facts: False
  tags:
    - repo
  tasks:
    - cdh_repos:
        host: 172.18.50.214
        user: admin
        password: admin
        repos:
          - http://archive.cloudera.com/kafka/parcels/1.4.0/
      register: repo_results
    - debug: var = repo_results

- name: Download Kafka parcel
  hosts: localhost
  gather_facts: False
  tags:
    - download
  tasks:
    - cdh_parcels:
        action: download
        host: 172.18.50.214
        user: admin
        password: admin
        parcels:
          KAFKA: 0.8.2.0-1.kafka1.4.0.p0.56
      register: download_results
    - debug: var = download_results

- name: Distibute Kafka parcel
  hosts: localhost
  gather_facts: False
  tags:
    - distribute
  tasks:
    - cdh_parcels:
        action: distribute
        host: 172.18.50.214
        user: admin
        password: admin
        parcels:
          KAFKA: 0.8.2.0-1.kafka1.4.0.p0.56
      register: distribute_results
    - debug: var = distribute_results

- name: Activate Kafka parcel
  hosts: localhost
  gather_facts: False
  tags:
    - activate
  tasks:
    - cdh_parcels:
        action: activate
        host: 172.18.50.214
        user: admin
        password: admin
        parcels:
          KAFKA: 0.8.2.0-1.kafka1.4.0.p0.56
      register: activate_results
    - debug: var = activate_results
