- name: Add Kafka repo
  hosts: localhost
  tags:
    - repo
  tasks:
    - cdh_repos:
      host: 172.18.50.214
      user: admin
      password: admin
      repos:
        - http://archive.cloudera.com/kafka/parcels/1.4.0/
      register: result
    - debug: var=result

- name: Download Kafka parcel
  hosts: localhost
  tags:
    - download
  tasks:
    - cdh_parcels:
        action: download
        host: 172.18.50.214
        user: admin
        password: admin
        parcels:
          KAFKA: 0.8.2.0-1.kafka1.4.0.p0.56
      register: result
    - debug: var=result    

- name: Distibute Kafka parcel
  hosts: localhost
  tags:
    - distribute
  tasks:
    - cdh_parcels:
        action: distribute
        host: 172.18.50.214
        user: admin
        password: admin
        parcels:
          KAFKA: 0.8.2.0-1.kafka1.4.0.p0.56
      register: result
    - debug: var=result

- name: Distibute Kafka parcel
  hosts: localhost
  tags:
    - activate
  tasks:
    - cdh_parcels:
        action: activate
        host: 172.18.50.214
        user: admin
        password: admin
        parcels:
          KAFKA: 0.8.2.0-1.kafka1.4.0.p0.56
      register: result
    - debug: var=result
